import "./src/models/barra";
import "./src/models/UserBase";
import "./src/models/service";
import "./src/models/productoNevera";
import "./src/models/vitrinaCounter";
import "./src/models/sede";
import "./src/models/user";
import "./src/models/venta";
import "./src/models/detalleVenta";
import "./src/models/citas";
//# sourceMappingURL=syncModels.d.ts.map